### ISSUE TITLE
Add API documentation and examples

### ISSUE THREAD

**Issue by JamesMGreene** [joyent/node-ip6addr#4]
Your "Inspired by [ipaddr.js](https://github.com/whitequark/ipaddr.js), ..." comment in the README suggests to me that I might be able to fully embrace the use of "ip6addr" and drop "ipaddr.js".  However, your README doesn't contain any real API documentation nor examples, which leaves me wondering -- not that "ipaddr.js" has much better documentation but I stumbled through getting into their usage.

Normally I would just go look at the test and/or code but their tests seem less than straight-forward to understand to me as well. :confused:

**Comment by melloc** [comment]
@JamesMGreene I meant to add some documentation a while ago, but kept putting it off. I've just fleshed out the [README](https://github.com/joyent/node-ip6addr/blob/master/README.md) with a description of available functions and methods, and added some examples where I thought they would be useful. If there's anything in it you find confusing, please let me know.

Sorry for not writing this up sooner!

**Comment by JamesMGreene** [comment]
:+1:
